"""
Alert management system with multiple notification channels.
Supports email, Slack, and webhook notifications with rate limiting.
"""
import asyncio
import json
import smtplib
from datetime import datetime, timedelta
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Dict, Any, List, Optional
from collections import defaultdict
import uuid

import aiohttp
from loguru import logger

from config.settings import settings
from supply_chain_analytics.models.schemas import AnomalyDetectionResult, SeverityLevel
from supply_chain_analytics.core.logger import LoggerSetup


class AlertCooldown:
    """Manages alert cooldown to prevent alert fatigue."""
    
    def __init__(self, cooldown_minutes: int = 15, max_per_hour: int = 20):
        self.cooldown_minutes = cooldown_minutes
        self.max_per_hour = max_per_hour
        self._last_alerts: Dict[str, datetime] = {}
        self._hourly_counts: Dict[str, List[datetime]] = defaultdict(list)
    
    def can_send(self, key: str) -> bool:
        """Check if alert can be sent for given key."""
        now = datetime.utcnow()
        
        # Clean old entries
        self._hourly_counts[key] = [
            t for t in self._hourly_counts[key]
            if now - t < timedelta(hours=1)
        ]
        
        # Check rate limit
        if len(self._hourly_counts[key]) >= self.max_per_hour:
            return False
        
        # Check cooldown
        if key in self._last_alerts:
            if now - self._last_alerts[key] < timedelta(minutes=self.cooldown_minutes):
                return False
        
        return True
    
    def record_sent(self, key: str) -> None:
        """Record that an alert was sent."""
        now = datetime.utcnow()
        self._last_alerts[key] = now
        self._hourly_counts[key].append(now)


class BaseNotifier:
    """Base class for notification channels."""
    
    async def send(
        self,
        subject: str,
        message: str,
        severity: SeverityLevel,
        metadata: Optional[Dict] = None,
    ) -> bool:
        raise NotImplementedError


class EmailNotifier(BaseNotifier):
    """Email notification channel."""
    
    def __init__(self):
        self.smtp_host = settings.alert.email_smtp_host
        self.smtp_port = settings.alert.email_smtp_port
        self.from_email = settings.alert.email_from
        self.to_email = settings.alert.email_to
        self.logger = LoggerSetup.get_logger("email_notifier")
    
    async def send(
        self,
        subject: str,
        message: str,
        severity: SeverityLevel,
        metadata: Optional[Dict] = None,
    ) -> bool:
        """Send email notification."""
        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = f"[{severity.value.upper()}] {subject}"
            msg["From"] = self.from_email
            msg["To"] = self.to_email
            
            # HTML email body
            severity_colors = {
                SeverityLevel.CRITICAL: "#dc3545",
                SeverityLevel.WARNING: "#ffc107",
                SeverityLevel.INFO: "#17a2b8",
                SeverityLevel.EMERGENCY: "#6f42c1",
            }
            
            html_body = f"""
            <html>
            <head></head>
            <body style="font-family: Arial, sans-serif;">
                <div style="
                    border-left: 5px solid {severity_colors.get(severity, '#6c757d')};
                    padding: 15px;
                    margin: 10px 0;
                    background-color: #f8f9fa;
                ">
                    <h3 style="color: #333;">{subject}</h3>
                    <p style="color: #666;">{message}</p>
                    <hr>
                    <p style="font-size: 12px; color: #999;">
                        Generated by Supply Chain Analytics Platform<br>
                        Time: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}
                    </p>
                </div>
            </body>
            </html>
            """
            
            msg.attach(MIMEText(html_body, "html"))
            
            # Send in thread to avoid blocking
            await asyncio.to_thread(
                self._send_smtp, msg
            )
            
            return True
            
        except Exception as e:
            self.logger.error(f"Failed to send email: {e}")
            return False
    
    def _send_smtp(self, msg: MIMEMultipart) -> None:
        """Send via SMTP (runs in thread)."""
        with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
            server.starttls()
            server.send_message(msg)


class SlackNotifier(BaseNotifier):
    """Slack webhook notification channel."""
    
    def __init__(self):
        self.webhook_url = settings.alert.slack_webhook_url
        self.logger = LoggerSetup.get_logger("slack_notifier")
        self._session: Optional[aiohttp.ClientSession] = None
    
    async def send(
        self,
        subject: str,
        message: str,
        severity: SeverityLevel,
        metadata: Optional[Dict] = None,
    ) -> bool:
        """Send Slack notification."""
        if not self.webhook_url:
            return False
        
        severity_emojis = {
            SeverityLevel.CRITICAL: "🔴",
            SeverityLevel.WARNING: "🟡",
            SeverityLevel.INFO: "🔵",
            SeverityLevel.EMERGENCY: "⚡",
        }
        
        color_map = {
            SeverityLevel.CRITICAL: "#dc3545",
            SeverityLevel.WARNING: "#ffc107",
            SeverityLevel.INFO: "#17a2b8",
            SeverityLevel.EMERGENCY: "#6f42c1",
        }
        
        try:
            payload = {
                "attachments": [
                    {
                        "color": color_map.get(severity, "#6c757d"),
                        "title": f"{severity_emojis.get(severity, '📢')} {subject}",
                        "text": message,
                        "fields": [
                            {
                                "title": "Severity",
                                "value": severity.value.upper(),
                                "short": True,
                            },
                            {
                                "title": "Time",
                                "value": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
                                "short": True,
                            },
                        ],
                        "footer": "Supply Chain Analytics Platform",
                    }
                ]
            }
            
            if metadata:
                for key, val in metadata.items():
                    payload["attachments"][0]["fields"].append({
                        "title": key,
                        "value": str(val),
                        "short": True,
                    })
            
            if self._session is None:
                self._session = aiohttp.ClientSession()
            
            async with self._session.post(
                self.webhook_url,
                json=payload,
                headers={"Content-Type": "application/json"},
            ) as response:
                return response.status == 200
                
        except Exception as e:
            self.logger.error(f"Failed to send Slack notification: {e}")
            return False


class AlertManager:
    """
    Central alert manager with:
    - Multiple notification channels
    - Rate limiting and cooldown
    - Severity-based routing
    - Alert deduplication
    """
    
    def __init__(self):
        self.logger = LoggerSetup.get_logger("alert_manager")
        self.cooldown = AlertCooldown(
            cooldown_minutes=settings.alert.alert_cooldown_minutes,
            max_per_hour=settings.alert.max_alerts_per_hour,
        )
        self.notifiers: Dict[str, BaseNotifier] = {
            "email": EmailNotifier(),
            "slack": SlackNotifier(),
        }
        self._sent_alerts: Dict[str, datetime] = {}
        self._alert_history: List[Dict[str, Any]] = []
    
    async def send_alert(
        self,
        title: str,
        message: str,
        severity: SeverityLevel = SeverityLevel.WARNING,
        channels: Optional[List[str]] = None,
        metadata: Optional[Dict[str, Any]] = None,
        dedup_key: Optional[str] = None,
    ) -> bool:
        """
        Send alert through configured channels.
        
        Args:
            title: Alert title
            message: Alert message body
            severity: Alert severity level
            channels: List of channels to use (None = all)
            metadata: Additional metadata
            dedup_key: Key for deduplication
        
        Returns:
            True if alert was sent to at least one channel
        """
        # Deduplication
        if dedup_key:
            if dedup_key in self._sent_alerts:
                last_sent = self._sent_alerts[dedup_key]
                if datetime.utcnow() - last_sent < timedelta(hours=1):
                    self.logger.debug(f"Alert deduplicated: {dedup_key}")
                    return False
        
        # Rate limiting
        rate_key = dedup_key or f"{title}_{severity.value}"
        if not self.cooldown.can_send(rate_key):
            self.logger.debug(f"Alert rate limited: {rate_key}")
            return False
        
        # Select channels based on severity
        if channels is None:
            if severity in [SeverityLevel.CRITICAL, SeverityLevel.EMERGENCY]:
                channels = ["email", "slack"]
            elif severity == SeverityLevel.WARNING:
                channels = ["slack"]
            else:
                channels = ["slack"]
        
        sent_any = False
        
        for channel in channels:
            if channel not in self.notifiers:
                continue
            
            try:
                success = await self.notifiers[channel].send(
                    subject=title,
                    message=message,
                    severity=severity,
                    metadata=metadata,
                )
                
                if success:
                    sent_any = True
                    self.logger.info(
                        f"Alert sent via {channel}: {title} [{severity.value}]"
                    )
            
            except Exception as e:
                self.logger.error(f"Failed to send alert via {channel}: {e}")
        
        if sent_any:
            self.cooldown.record_sent(rate_key)
            if dedup_key:
                self._sent_alerts[dedup_key] = datetime.utcnow()
            
            # Store in history
            self._alert_history.append({
                "title": title,
                "message": message,
                "severity": severity.value,
                "channels": channels,
                "timestamp": datetime.utcnow().isoformat(),
                "metadata": metadata or {},
            })
            
            # Limit history size
            if len(self._alert_history) > 1000:
                self._alert_history = self._alert_history[-1000:]
        
        return sent_any
    
    async def send_anomaly_alert(
        self, anomaly: AnomalyDetectionResult
    ) -> bool:
        """Send alert for detected anomaly."""
        title = f"Anomaly Detected: {anomaly.metric_name}"
        
        message = (
            f"Anomaly detected in {anomaly.metric_name}.\n"
            f"Entity: {anomaly.entity_id}\n"
            f"Actual Value: {anomaly.actual_value:.2f}\n"
            f"Expected Value: {anomaly.expected_value:.2f}\n"
            f"Deviation: {anomaly.deviation_percentage:.1f}%\n"
            f"Confidence: {anomaly.confidence_score:.1%}\n\n"
            f"Recommendation: {anomaly.recommendation or 'Investigate the anomaly.'}"
        )
        
        metadata = {
            "Metric": anomaly.metric_name,
            "Entity": anomaly.entity_id,
            "Deviation %": f"{anomaly.deviation_percentage:.1f}%",
            "Z-Score": f"{anomaly.z_score:.2f}",
            "Algorithm": anomaly.algorithm_used,
        }
        
        return await self.send_alert(
            title=title,
            message=message,
            severity=anomaly.severity,
            metadata=metadata,
            dedup_key=f"anomaly_{anomaly.metric_name}_{anomaly.entity_id}",
        )
    
    async def send_health_check_alert(self, component: str, status: str) -> bool:
        """Send system health check alert."""
        severity = SeverityLevel.CRITICAL if status != "healthy" else SeverityLevel.INFO
        return await self.send_alert(
            title=f"Health Check: {component}",
            message=f"Component '{component}' is {status}.",
            severity=severity,
            dedup_key=f"health_{component}",
        )
    
    def get_alert_history(
        self,
        limit: int = 100,
        severity: Optional[SeverityLevel] = None,
    ) -> List[Dict[str, Any]]:
        """Get alert history with optional filtering."""
        history = self._alert_history
        
        if severity:
            history = [a for a in history if a["severity"] == severity.value]
        
        return history[-limit:]
    
    def get_alert_stats(self) -> Dict[str, Any]:
        """Get alert statistics."""
        total = len(self._alert_history)
        by_severity = defaultdict(int)
        by_channel = defaultdict(int)
        
        for alert in self._alert_history:
            by_severity[alert["severity"]] += 1
            for channel in alert.get("channels", []):
                by_channel[channel] += 1
        
        return {
            "total_alerts": total,
            "by_severity": dict(by_severity),
            "by_channel": dict(by_channel),
            "last_alert": self._alert_history[-1] if self._alert_history else None,
        }